name: movies_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  provider:
  go_router: ^14.6.2
  shared_preferences: ^2.3.5
  flutter_svg:
  fluttertoast:
  intl:
  dio:
  infinite_scroll_pagination: ^4.1.0
  cached_network_image:
  youtube_player_flutter: ^9.1.1
  book_my_seat: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/svg/bottom-navigation/
    - assets/svg/booking/

  fonts:
   - family: Poppins
     fonts:
       - asset: assets/font/poppins/Poppins-Black.ttf
       - asset: assets/font/poppins/Poppins-BlackItalic.ttf
       - asset: assets/font/poppins/Poppins-Bold.ttf
       - asset: assets/font/poppins/Poppins-BoldItalic.ttf
       - asset: assets/font/poppins/Poppins-ExtraBoldItalic.ttf
       - asset: assets/font/poppins/Poppins-ExtraBold.ttf
       - asset: assets/font/poppins/Poppins-ExtraLight.ttf
       - asset: assets/font/poppins/Poppins-ExtraLightItalic.ttf
       - asset: assets/font/poppins/Poppins-Italic.ttf
       - asset: assets/font/poppins/Poppins-Light.ttf
       - asset: assets/font/poppins/Poppins-LightItalic.ttf
       - asset: assets/font/poppins/Poppins-Medium.ttf
       - asset: assets/font/poppins/Poppins-MediumItalic.ttf
       - asset: assets/font/poppins/Poppins-Regular.ttf
       - asset: assets/font/poppins/Poppins-SemiBold.ttf
       - asset: assets/font/poppins/Poppins-SemiBoldItalic.ttf
       - asset: assets/font/poppins/Poppins-Thin.ttf
       - asset: assets/font/poppins/Poppins-ThinItalic.ttf




